version: '3'
services:
  web:
    image: webdevops/php-nginx-dev:7.2
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/app
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge